#!/usr/bin/env bash
# generate_report.sh — Runs analyze.sh over all test_data logs and produces
# a text summary and an HTML report in output/

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
ANALYZE="$SCRIPT_DIR/analyze.sh"
TEST_DATA="$PROJECT_ROOT/test_data"
OUTPUT_DIR="$PROJECT_ROOT/output"
HTML_REPORT="$OUTPUT_DIR/report.html"
TEXT_REPORT="$OUTPUT_DIR/summary.txt"

mkdir -p "$OUTPUT_DIR"

# Check for log files
LOG_FILES=$(find "$TEST_DATA" -name "*.log" | sort)
if [ -z "$LOG_FILES" ]; then
    echo "No .log files found in $TEST_DATA"
    exit 1
fi

# ── Text summary ──────────────────────────────────────────────────────────────

echo "=== RISC-V Log Analyzer — Batch Summary ===" > "$TEXT_REPORT"
echo "Generated: $(date '+%Y-%m-%d %H:%M:%S')"    >> "$TEXT_REPORT"
echo ""                                             >> "$TEXT_REPORT"

for log in $LOG_FILES; do
    echo "──────────────────────────────────────────" >> "$TEXT_REPORT"
    bash "$ANALYZE" "$log" 2>/dev/null               >> "$TEXT_REPORT" || true
    echo ""                                          >> "$TEXT_REPORT"
done

echo "Text summary written to: $TEXT_REPORT"

# ── HTML report ───────────────────────────────────────────────────────────────

cat > "$HTML_REPORT" << 'EOF'
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>RISC-V Simulation Log Report</title>
<style>
  body   { font-family: monospace; background: #1e1e2e; color: #cdd6f4; margin: 2rem; }
  h1     { color: #89b4fa; }
  h2     { color: #cba6f7; margin-top: 2rem; }
  table  { border-collapse: collapse; width: 100%; margin-top: 1rem; }
  th     { background: #313244; color: #89dceb; padding: .5rem 1rem; text-align: left; }
  td     { padding: .4rem 1rem; border-bottom: 1px solid #45475a; }
  tr:hover td { background: #313244; }
  .pass  { color: #a6e3a1; font-weight: bold; }
  .fail  { color: #f38ba8; font-weight: bold; }
  .skip  { color: #f9e2af; }
  footer { margin-top: 3rem; font-size: .8em; color: #6c7086; }
</style>
</head>
<body>
<h1>RISC-V Simulation Log Report</h1>
EOF

for log in $LOG_FILES; do
    # Get CSV data from analyze.sh
    csv=$(bash "$ANALYZE" "$log" --format csv 2>/dev/null || true)

    # Helper to pull a value by key from the CSV
    get_val() { echo "$csv" | awk -F',' -v k="$1" '$1==k { print $2; exit }'; }

    total=$(get_val total)
    passed=$(get_val passed)
    failed=$(get_val failed)
    skipped=$(get_val skipped)
    pass_pct=$(get_val pass_rate_pct)
    min_t=$(get_val min_time_s)
    max_t=$(get_val max_time_s)
    avg_t=$(get_val avg_time_s)
    min_test=$(get_val min_time_test)
    max_test=$(get_val max_time_test)

    # Pick a pass/fail label
    verdict="PASS"
    if [ "${failed:-0}" -gt 0 ]; then
        verdict="FAIL"
    fi

    logname=$(basename "$log")

    cat >> "$HTML_REPORT" << SECTION
<h2>$logname — $verdict</h2>
<table>
  <tr><th>Metric</th><th>Value</th></tr>
  <tr><td>Total tests</td><td>$total</td></tr>
  <tr><td>Passed</td><td class="pass">$passed ($pass_pct%)</td></tr>
  <tr><td>Failed</td><td class="fail">$failed</td></tr>
  <tr><td>Skipped</td><td class="skip">$skipped</td></tr>
SECTION

    # Add timing rows only when data is available
    if [ -n "$min_t" ]; then
        cat >> "$HTML_REPORT" << TIMING
  <tr><td>Min time</td><td>${min_t}s ($min_test)</td></tr>
  <tr><td>Max time</td><td>${max_t}s ($max_test)</td></tr>
  <tr><td>Avg time</td><td>${avg_t}s</td></tr>
TIMING
    fi

    # Per-test result rows
    echo "  <tr><th colspan='2'>Per-test results</th></tr>" >> "$HTML_REPORT"

    echo "$csv" | awk -F',' '$1=="PASS" || $1=="FAIL" || $1=="SKIP"' | \
    while IFS=',' read -r result name time_s; do
        css=$(echo "$result" | tr '[:upper:]' '[:lower:]')
        echo "  <tr><td class='$css'>$result</td><td>$name (${time_s}s)</td></tr>"
    done >> "$HTML_REPORT"

    echo "</table>" >> "$HTML_REPORT"
done

cat >> "$HTML_REPORT" << 'EOF'
<footer>Generated by riscv-log-analyzer · generate_report.sh</footer>
</body>
</html>
EOF

echo "HTML report written to: $HTML_REPORT"
