#!/usr/bin/env bash
# generate_report.sh — Runs analyze.sh over all test_data logs and produces
# a combined text summary AND an HTML report in output

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
ANALYZE="$SCRIPT_DIR/analyze.sh"
TEST_DATA="$PROJECT_ROOT/test_data"
OUTPUT_DIR="$PROJECT_ROOT/output"

mkdir -p "$OUTPUT_DIR"

HTML_REPORT="$OUTPUT_DIR/report.html"
TEXT_REPORT="$OUTPUT_DIR/summary.txt"

# ─── Collect results from every .log file ────────────────────────────────────
declare -a LOG_FILES=()
while IFS= read -r -d '' f; do
    LOG_FILES+=("$f")
done < <(find "$TEST_DATA" -name "*.log" -print0 | sort -z)

if [[ ${#LOG_FILES[@]} -eq 0 ]]; then
    echo "No .log files found in $TEST_DATA" >&2
    exit 1
fi

# ─── Text summary ─────────────────────────────────────────────────────────────
{
    echo "=== RISC-V Log Analyzer — Batch Summary ==="
    echo "Generated: $(date '+%Y-%m-%d %H:%M:%S')"
    echo ""

    for log in "${LOG_FILES[@]}"; do
        echo "──────────────────────────────────────────"
        # analyze.sh exits 1 on failures; capture output without aborting this script
        bash "$ANALYZE" "$log" 2>/dev/null || true
        echo ""
    done
} > "$TEXT_REPORT"

echo "Text summary written to: $TEXT_REPORT"

# ─── HTML report ──────────────────────────────────────────────────────────────
# Parse CSV output for each log to build a structured table.

cat > "$HTML_REPORT" <<'HTMLEOF'
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>RISC-V Simulation Log Report</title>
<style>
  body { font-family: monospace; background: #1e1e2e; color: #cdd6f4; margin: 2rem; }
  h1   { color: #89b4fa; }
  h2   { color: #cba6f7; margin-top: 2rem; }
  table{ border-collapse: collapse; width: 100%; margin-top: 1rem; }
  th   { background: #313244; color: #89dceb; padding: .5rem 1rem; text-align: left; }
  td   { padding: .4rem 1rem; border-bottom: 1px solid #45475a; }
  tr:hover td { background: #313244; }
  .pass{ color: #a6e3a1; font-weight: bold; }
  .fail{ color: #f38ba8; font-weight: bold; }
  .skip{ color: #f9e2af; }
  .verdict-pass { color: #a6e3a1; font-size: 1.2em; }
  .verdict-fail { color: #f38ba8; font-size: 1.2em; }
  footer { margin-top: 3rem; font-size: .8em; color: #6c7086; }
</style>
</head>
<body>
<h1>🖥 RISC-V Simulation Log Report</h1>
HTMLEOF

for log in "${LOG_FILES[@]}"; do
    # Get CSV output
    csv=$(bash "$ANALYZE" "$log" --format csv 2>/dev/null || true)

    # extract a value from the CSV
    get_val() { echo "$csv" | awk -F',' -v k="$1" '$1==k{print $2}' | head -1; }

    total=$(get_val total)
    passed=$(get_val passed)
    failed=$(get_val failed)
    skipped=$(get_val skipped)
    pass_pct=$(get_val pass_rate_pct)
    min_t=$(get_val min_time_s)
    max_t=$(get_val max_time_s)
    avg_t=$(get_val avg_time_s)
    min_test=$(get_val min_time_test)
    max_test=$(get_val max_time_test)

    verdict_class="verdict-pass"
    verdict_label="✓ PASS"
    [[ "${failed:-0}" -gt 0 ]] && { verdict_class="verdict-fail"; verdict_label="✗ FAIL"; }

    logname=$(basename "$log")

    cat >> "$HTML_REPORT" <<SECTION
<h2>📄 $logname</h2>
<p class="$verdict_class">$verdict_label</p>
<table>
  <tr><th>Metric</th><th>Value</th></tr>
  <tr><td>Total tests</td><td>$total</td></tr>
  <tr><td>Passed</td><td class="pass">$passed ($pass_pct%)</td></tr>
  <tr><td>Failed</td><td class="fail">$failed</td></tr>
  <tr><td>Skipped</td><td class="skip">$skipped</td></tr>
SECTION

    if [[ -n "$min_t" ]]; then
        cat >> "$HTML_REPORT" <<TIMING
  <tr><td>Min time</td><td>${min_t}s &nbsp;($min_test)</td></tr>
  <tr><td>Max time</td><td>${max_t}s &nbsp;($max_test)</td></tr>
  <tr><td>Avg time</td><td>${avg_t}s</td></tr>
TIMING
    fi

    # Per-test rows
    echo "  <tr><th colspan='2'>Per-test results</th></tr>" >> "$HTML_REPORT"
    while IFS=',' read -r result name time_s; do
        [[ "$result" == "result" || -z "$result" ]] && continue
        css_class=$(echo "$result" | tr '[:upper:]' '[:lower:]')
        echo "  <tr><td class='$css_class'>$result</td><td>$name &nbsp;<em>${time_s}s</em></td></tr>" >> "$HTML_REPORT"
    done < <(echo "$csv" | awk -F',' 'NR>1 && ($1=="PASS"||$1=="FAIL"||$1=="SKIP"){print}')

    echo "</table>" >> "$HTML_REPORT"
done

cat >> "$HTML_REPORT" <<'HTMLEOF'
<footer>Generated by riscv-log-analyzer · generate_report.sh</footer>
</body>
</html>
HTMLEOF

echo "HTML report written to:  $HTML_REPORT"
